### ISSUE TITLE
Gerber from EscornaCPU 2.20 rejected from PCBWay.

### ISSUE THREAD

**Issue by juanmard** [escornabot/electronics#1]
Message from PCBWay:

> the copper part is too close with keepout line. Pls revise your pcb border to be bigger，the distance requires to be >=0.25mm

Explain image above.

![225937131t](https://user-images.githubusercontent.com/17770252/42343949-0ceb91ac-809b-11e8-97eb-8ed688bbf111.jpg)

In other way, file _**"escorna_cpu_2_20.kicad_pcb"**_ open in blank board with **KiCAD v4.0.7**

**Comment by ghost** [comment]
que no te vacilen

llevan hechas con ese archivo cientos de placas.

[image: image.png]



O xov., 5/07/2018 ás 21:34, Juan Manuel Rico (<notifications@github.com>)
escribiu:

**Comment by juanmard** [comment]
Me habrá tocado el chino "chisquilloso" en PCBWay... :(
La cuestión es que he ido a modificarla y me he dado cuenta que los esquemáticos están hechos en Eagle (uso KiCAD)... pero hay un fichero PCB exportado a KiCAD que tampoco he podido abrir. :(

¿Tienes compartida la versión 2.20 a PCBWay? :)

**Comment by ghost** [comment]
Que te parece así:
[image: image.png]


O xov., 5/07/2018 ás 21:53, Juan Manuel Rico (<notifications@github.com>)
escribiu:

**Comment by juanmard** [comment]
No me salen tus imágenes.  :(

**Comment by ghost** [comment]
Modifico la placa para que no tengamos problemas y la subo en unos minutos.

**Comment by ghost** [comment]
Todo modificado y subido, si encuentras algún erro.. avisa
Gracias por todo

O xov., 5/07/2018 ás 22:21, Juan Manuel Rico (<notifications@github.com>)
escribiu:

**Comment by juanmard** [comment]
De nada, gracias a ti.
Antes de que lo modificaras he hecho otro intento y ahora me lo rechazan por otra cosa.

> missing the right column line for Keep out layer.

![040543454t](https://user-images.githubusercontent.com/17770252/42348171-bbffdf9c-80a8-11e8-9b37-01da01f9f1b0.jpg)

Voy a volverlo a intentar con tus nuevas modificaciones.

**Comment by ghost** [comment]
intentaré subirlo a shared

O xov., 5/07/2018 ás 23:12, Juan Manuel Rico (<notifications@github.com>)
escribiu:

**Comment by juanmard** [comment]
No tengo suerte... con las últimas modificaciones me han enviado dos errores.

> missing the right column line for Keep out layer.

![040543454t](https://user-images.githubusercontent.com/17770252/42351497-87aca2d6-80b5-11e8-905b-cb7bf1bdf27f.jpg)

![053139309t](https://user-images.githubusercontent.com/17770252/42351498-87d74d42-80b5-11e8-96f3-d704dde6b67b.jpg)

El fichero de KiCAD también ha desaparecido al hacer el "pull" del proyecto. :(

**Comment by ghost** [comment]
Ya lo tienes en PCBway

https://www.pcbway.com/project/shareproject/Escorna_CPU_2_20_Gerber.html

O ven., 6/07/2018 ás 00:44, Juan Manuel Rico (<notifications@github.com>)
escribiu:

**Comment by juanmard** [comment]
Perfecto, ahora sí han dejado de quejarse. ;)
Gracias.
